- name: Restart HTTPD (RedHat/CentOS)
  service: name={{ redhat_apache }} state=restarted
  when: "{{ redhat_os }}"
  ignore_errors:
- name: Restart Apache2
  service: name={{ debian_apache }} state=restarted
  when: "{{ debian_os }}"
- name: Install Telnet
  yum: pkg=telnet state=latest
